version: '3'

services:
  tondnode0:
    container_name: tondnode0
    image: "tepleton/tondnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-tond.log}
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  tondnode1:
    container_name: tondnode1
    image: "tepleton/tondnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-tond.log}
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  tondnode2:
    container_name: tondnode2
    image: "tepleton/tondnode"
    environment:
      - ID=2
      - LOG=$${LOG:-tond.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  tondnode3:
    container_name: tondnode3
    image: "tepleton/tondnode"
    environment:
      - ID=3
      - LOG=$${LOG:-tond.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

